### ISSUE TITLE
/config/configuration.yaml ?? 

### ISSUE THREAD

**Issue by gogoX1** [enes-oerdek/Home-Assistant-Helium-Integration#1]
I'm relatively new to this, can you tell me what I'm doing wrong?
![image](https://github.com/enes-oerdek/Home-Assistant-Helium-Integration/assets/63733089/a6aba805-3e0e-4edd-a6b6-a77f25e64015)
![image](https://github.com/enes-oerdek/Home-Assistant-Helium-Integration/assets/63733089/c027a5d6-2c88-4878-ab13-8cc63d14f8f1)

thank you already

**Comment by enes-oerdek** [comment]
@gogoX1  I am so sorry about the confusion. You need to also remove the brackets, so that you have something like this (replace with your public key):
```yaml
sensor:
  - platform: helium_solana
    wallets:
    - rAwOnpD26GH8FcEo1H4ng3MPPsN8C5KdZ7N7MqAS
```

I just updated the readme. Also please be mindful about the spaces. Do not use tabs for aligning your characters. Rather make spaces. The yaml format is sensitive about whitespace.

Can you please let me know, whether this worked?
